### ISSUE TITLE
code simplification

### ISSUE THREAD

**Issue by arademaker** [EricZinda/Perplexity#1]
https://github.com/EricZinda/Perplexity/blob/58e6967f4fde58bf90e42c9793bbd01d720daf6c/perplexity/tree_algorithm_zinda2020.py#L546-L548

```python
% python3
Python 3.9.6 (default, Nov 10 2023, 13:38:27) 
>>> d = dict(a = 1, b = 2)
>>> d
{'a': 1, 'b': 2}
>>> list(d.values())
[1, 2]
```

**Comment by EricZinda** [comment]
Thanks! No idea why I wrote it that way ...
